import { Montserrat } from 'next/font/google';
import './globals.css';
import Navigation from './components/Navigation/Navigation';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const montserrat = Montserrat({
	subsets: ['latin'],
	display: 'swap',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' className={`min-h-full ${montserrat.className}`}>
			<body className='container mx-auto px-4 min-h-screen'>
				<Navigation />
				{children}
			</body>
		</html>
	);
}
